// src/services/mockData.ts
// Mock data matching the BlueOcean review_output JSON schema

import type { Report } from '@/types';
import { ReportStatus } from '@/types';

export const MOCK_REPORTS: Report[] = [
  {
    id: 'RPT-2026-0601',
    title: 'China Quantum Computing: Strategic Landscape & Investment Outlook',
    version: 'v1.2',
    status: ReportStatus.NeedsHumanReview,
    humanStatus: 'Pending',
    aiScore: 88.8,
    aiGrade: 'Silver',
    commentCount: 0,
    lastUpdated: '2026-06-02T23:37:34',
    publishReady: false,
    aiReview: {
      scores: {
        overall_score: 88.8,
        grade: 'Silver',
        components: {
          research_quality: 92,
          strategic_insight: 90,
          source_quality: 85,
          writing_quality: 95,
          design_quality: 85,
          executive_readiness: 88,
        },
      },
      recommendations: {
        strengths: [
          "Comprehensive overview of China's quantum computing sector",
          'Clear discussion of technological advancements and government funding',
          'Well-articulated investment thesis with risk assessment',
          'Effective use of technical analogies for executive readers',
        ],
        weaknesses: [
          'Limited discussion of commercialization potential and timelines',
          'Lack of quantum software ecosystem analysis',
          'Over-reliance on state funding data; private sector underrepresented',
          'No discussion of quantum hardware supply chain risks',
        ],
        priority_improvements: [
          {
            issue: 'Lack of clear definitions and explanations',
            impact: 'Reduces accessibility for non-technical executive readers',
            suggested_fix: 'Provide clear definitions and explanations of key technical terms',
            priority_level: 'High',
          },
          {
            issue: 'Too technical for non-experts',
            impact: 'Limits audience reach',
            suggested_fix: 'Add executive summary in plain language',
            priority_level: 'Medium',
          },
          {
            issue: 'Missing commercialization timeline',
            impact: 'Investment decisions lack timing anchor',
            suggested_fix: 'Add a scenario-based timeline to 2030',
            priority_level: 'Low',
          },
        ],
        executive_readiness: {
          board_members: true,
          ministers: false,
          ceos: true,
          sovereign_wealth_funds: false,
          senior_executives: true,
          justification:
            'Suitable for board and senior executive readers with energy/tech background. Ministers and SWF audiences require simplified language and stronger GCC relevance framing.',
        },
      },
      dataGaps: [
        '[Medium] Quantum computing market size for financial modeling applications',
        '[Low] Patent citation impact for China vs US comparison',
      ],
      writingFlaws: [
        '[Low] Vague statements in Key Highlights without concrete definitions',
        '[Medium] Unexplained technical jargon in hardware section',
      ],
      strategicGaps: [
        '[High] Missing key challenges in Chinese quantum computing development',
        '[Medium] No leverage strategy for quantum communication strengths',
      ],
      gccGaps: ['Government funding section does not explain relevance to GCC stakeholders'],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 2, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `China's quantum computing sector has emerged as a primary strategic focus under the 14th Five-Year Plan, with government funding exceeding $15 billion. Superconducting qubit platforms remain dominant, led by USTC and Origin Quantum, while photonic and topological approaches are gaining traction among academic spinouts.\n\nThe nation leads globally in quantum communication patents and has deployed the world's longest quantum-secured communication backbone (Beijing–Shanghai). However, China trails the US significantly in quantum computing software and algorithmic development, limiting near-term commercial applications.\n\nKey near-term applications are concentrated in financial modeling, drug discovery, and logistics optimization — areas where Chinese cloud providers (Alibaba, Baidu, Huawei) are actively piloting quantum cloud services.`,
        },
        {
          heading: 'Hardware Landscape',
          body: `Superconducting qubit systems dominate China's quantum hardware landscape. USTC's Zuchongzhi processor reached 66-qubit performance in controlled experiments. Origin Quantum, a Hefei-based spinout, offers commercial systems via cloud and on-premise deployments.\n\nPhotonic approaches from Jiuzhang-series processors have demonstrated quantum advantage in Gaussian boson sampling, while topological qubit research remains largely pre-commercial. Error correction rates remain significantly below fault-tolerant thresholds across all platforms.`,
        },
        {
          heading: 'Government Funding & Policy',
          body: `Under the 14th Five-Year Plan (2021–2025), China has allocated over ¥100 billion ($15B+) to quantum technology, with a strong emphasis on quantum communication infrastructure and defense applications.\n\nThe national quantum backbone network covers over 2,000 km of fiber with satellite integration (Micius). Policy direction prioritizes communication security over commercial computing applications, creating a bifurcated development trajectory.`,
        },
        {
          heading: 'Competitive Position vs. US',
          body: `China leads in quantum communication patents (60%+ global share) and government-funded infrastructure. The US leads comprehensively in quantum computing software (Qiskit, Cirq, PennyLane), algorithmic development, error mitigation, and commercial cloud QaaS ecosystem.\n\nIBM, Google, and IonQ collectively outpace China on hardware roadmaps targeting fault-tolerant quantum computing. The talent pipeline asymmetry is growing — US benefits from global talent acquisition while China faces a brain drain risk as leading researchers relocate abroad.`,
        },
        {
          heading: 'Strategic Recommendations',
          body: `1. Monitor SPARC and IBM Condor milestones as calibration benchmarks for China's hardware roadmap.\n2. Engage Origin Quantum and Baidu Quantum as preferred QaaS evaluation partners for financial services use cases.\n3. Track quantum communication policy developments for potential GCC bilateral cooperation opportunities.\n4. Build internal quantum literacy programs now to reduce the talent gap when commercial applications mature (2029–2032 window).`,
        },
        {
          heading: 'Disclaimer',
          isDisclaimer: true,
          body: `This report has been prepared by BlueOcean Research for internal decision-making purposes only. The information contained herein is based on publicly available sources and AI-assisted analysis as of the report date. It does not constitute financial, legal, or investment advice.`,
        },
      ],
    },
    comments: [],
  },
  {
    id: 'RPT-2026-0602',
    title: 'Nuclear Fusion Commercialization: Energy Disruption & Investment Strategy',
    version: 'v1.0',
    status: ReportStatus.AIReviewed,
    humanStatus: 'Not Started',
    aiScore: 85.5,
    aiGrade: 'Silver',
    commentCount: 0,
    lastUpdated: '2026-06-01T17:29:00',
    publishReady: false,
    aiReview: {
      scores: {
        overall_score: 85.5,
        grade: 'Silver',
        components: {
          research_quality: 85,
          strategic_insight: 88,
          source_quality: 80,
          writing_quality: 90,
          design_quality: 85,
          executive_readiness: 85,
        },
      },
      recommendations: {
        strengths: [
          'Strong understanding of nuclear fusion commercialization and strategic implications',
          'Valuable strategic insights into impact on energy markets and geopolitics',
          'Well-written, concise, and accessible to executive readers',
          'Clear and logical structure with actionable recommendations',
        ],
        weaknesses: [
          'Lacks in-depth analysis of specific technical challenges',
          'Does not explicitly cite sources, reducing source quality score',
          'Relies on general industry trends without concrete data or expert quotes',
          'No visual elements to enhance comprehension',
        ],
        priority_improvements: [
          {
            issue: 'Lack of in-depth technical analysis',
            impact: 'Reduces credibility for technical decision-makers',
            suggested_fix: 'Add detailed analysis of tritium breeding, materials resilience, and licensing barriers',
            priority_level: 'High',
          },
          {
            issue: 'Insufficient evidence strength',
            impact: 'Decreases report persuasiveness',
            suggested_fix: 'Incorporate data, statistics, and expert quotes',
            priority_level: 'Medium',
          },
        ],
        executive_readiness: {
          board_members: true,
          ministers: false,
          ceos: true,
          sovereign_wealth_funds: false,
          senior_executives: true,
          justification: 'Suitable for board and C-suite readers with energy industry background.',
        },
      },
      dataGaps: ['[High] No tritium supply chain cost data', '[Medium] Missing LCOE comparison fusion vs fission'],
      writingFlaws: ['[Low] Passive voice in recommendations section'],
      strategicGaps: ['[High] No GCC energy transition linkage'],
      gccGaps: ['No explicit connection to GCC hydrocarbon export strategy'],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 1, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `Nuclear fusion is transitioning from a long-term scientific aspiration to a tangible commercial goal. Driven by private investment and advances in high-temperature superconductors, AI-driven plasma control, and additive manufacturing, well-funded ventures including Commonwealth Fusion Systems, TAE Technologies, and Helion Energy are targeting net-energy gain and pilot plants within the next decade.\n\nFusion could achieve cost parity with renewables by the late 2030s under optimistic scenarios, promising near-limitless, carbon-free baseload power that could reshape energy geopolitics.`,
        },
        {
          heading: 'Technology Overview',
          body: `Magnetic confinement fusion (tokamak) remains the dominant approach, with ITER representing the largest international collaboration. Private tokamak ventures are pursuing compact high-field designs enabled by REBCO superconductors.\n\nKey technical barriers: tritium breeding self-sufficiency, plasma-facing materials resilience under neutron bombardment, and regulatory licensing frameworks for fusion reactors.`,
        },
        {
          heading: 'Strategic Implications',
          body: `Energy Security: Fusion baseload could reduce strategic dependence on hydrocarbon-producing regions, with long-term implications for GCC export revenues.\n\nInvestment Opportunity: Early-stage fusion equity (CFS, Helion, TAE) offers high-risk/high-reward exposure. SPARC net-energy demonstration (targeted 2025) is a key de-risking milestone.`,
        },
        {
          heading: 'Disclaimer',
          isDisclaimer: true,
          body: `This report is for internal BlueOcean Research use only. All projections are model-based estimates and subject to significant uncertainty. Not investment advice.`,
        },
      ],
    },
    comments: [],
  },
  {
    id: 'RPT-2026-0603',
    title: 'GCC Sovereign Wealth Fund Digital Transformation Benchmarking',
    version: 'v2.1',
    status: ReportStatus.Approved,
    humanStatus: 'Approved',
    aiScore: 91.2,
    aiGrade: 'Gold',
    commentCount: 3,
    lastUpdated: '2026-06-03T09:15:00',
    publishReady: true,
    aiReview: {
      scores: {
        overall_score: 91.2,
        grade: 'Gold',
        components: {
          research_quality: 93,
          strategic_insight: 92,
          source_quality: 88,
          writing_quality: 94,
          design_quality: 90,
          executive_readiness: 92,
        },
      },
      recommendations: {
        strengths: [
          'Comprehensive benchmarking across 6 major GCC sovereign wealth funds',
          'Original primary research with direct fund interviews',
          'Clear strategic recommendations tailored to regional context',
          'Strong executive readiness with minister-level language',
        ],
        weaknesses: [
          'Limited peer comparison outside GCC (Norway GPFG, Singapore Temasek)',
          'Technology adoption metrics rely on self-reported data',
        ],
        priority_improvements: [
          {
            issue: 'No global peer comparison',
            impact: 'Limits contextual benchmarking',
            suggested_fix: 'Add comparative table: ADIA, QIA, PIF vs GPFG, GIC, Temasek',
            priority_level: 'Medium',
          },
        ],
        executive_readiness: {
          board_members: true,
          ministers: true,
          ceos: true,
          sovereign_wealth_funds: true,
          senior_executives: true,
          justification: 'Gold-grade executive readiness. Suitable for all target audiences.',
        },
      },
      dataGaps: [],
      writingFlaws: [],
      strategicGaps: [],
      gccGaps: [],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 3, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `GCC sovereign wealth funds are rapidly advancing their digital transformation agendas, with cumulative technology investment exceeding $8 billion across ADIA, QIA, PIF, Mubadala, ADQ, and ICD in 2025.\n\nKey transformation pillars include AI-driven portfolio analytics, cloud infrastructure migration, ESG data platforms, and digital asset custody. PIF leads on innovation velocity; ADIA leads on technology governance maturity.`,
        },
        {
          heading: 'Key Findings',
          body: `PIF ranks highest in AI adoption velocity, driven by Vision 2030 mandate and $1B+ technology investment runway. ADIA leads in governance maturity with the most robust digital risk and compliance framework.\n\nCommon gaps across all funds: quantum computing readiness, real-time portfolio risk analytics, and ESG data standardization.`,
        },
        {
          heading: 'Strategic Recommendations',
          body: `1. Establish a GCC SWF Technology Working Group to share non-competitive best practices.\n2. Prioritize quantum computing exploration programs now, targeting commercial readiness by 2030.\n3. Standardize ESG data collection across portfolio companies to enable fund-level reporting by 2027.`,
        },
        {
          heading: 'Disclaimer',
          isDisclaimer: true,
          body: `Prepared for internal use. Interview data has been anonymized per participant agreements.`,
        },
      ],
    },
    comments: [
      {
        id: 'c1',
        reportId: 'RPT-2026-0603',
        version: 'v2.1',
        section: 'Key Findings',
        text: 'Add GPFG and GIC as comparison benchmarks. The absence of global peers weakens the contextual framing.',
        priority: 'Medium',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-03T08:45:00',
        status: 'resolved',
      },
      {
        id: 'c2',
        reportId: 'RPT-2026-0603',
        version: 'v2.1',
        section: 'Strategic Recommendations',
        text: 'Recommendation 4 on AI CoE needs budget range estimates to be actionable.',
        priority: 'High',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-03T08:52:00',
        status: 'resolved',
      },
      {
        id: 'c3',
        reportId: 'RPT-2026-0603',
        version: 'v2.1',
        section: 'Executive Summary',
        text: 'The $8B figure needs a footnote or inline citation.',
        priority: 'Low',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-03T09:01:00',
        status: 'resolved',
      },
    ],
  },
  {
    id: 'RPT-2026-0604',
    title: 'GCC AI Regulation Landscape: Policy Gaps and Opportunity Map',
    version: 'v1.0',
    status: ReportStatus.ReadyToPublish,
    humanStatus: 'Approved',
    aiScore: 78.4,
    aiGrade: 'Bronze',
    commentCount: 1,
    lastUpdated: '2026-06-04T10:30:00',
    publishReady: true,
    aiReview: {
      scores: {
        overall_score: 78.4,
        grade: 'Bronze',
        components: {
          research_quality: 80,
          strategic_insight: 82,
          source_quality: 72,
          writing_quality: 85,
          design_quality: 75,
          executive_readiness: 76,
        },
      },
      recommendations: {
        strengths: [
          'Timely topic with strong regional policy relevance',
          'Good coverage of UAE, Saudi Arabia, and Qatar regulatory frameworks',
          'Actionable gap analysis for policy stakeholders',
        ],
        weaknesses: [
          'Limited coverage of Bahrain, Kuwait, Oman AI policy developments',
          'No comparative analysis with EU AI Act or US NIST framework',
        ],
        priority_improvements: [
          {
            issue: 'Incomplete GCC coverage',
            impact: 'Report appears UAE/Saudi-centric',
            suggested_fix: 'Add section on Bahrain AI sandbox and Oman digital economy strategy',
            priority_level: 'High',
          },
        ],
        executive_readiness: {
          board_members: true,
          ministers: true,
          ceos: false,
          sovereign_wealth_funds: false,
          senior_executives: true,
          justification: 'Suitable for ministerial and board audiences. CEO audience requires more quantitative business impact framing.',
        },
      },
      dataGaps: ['[High] No enforcement data or penalty case studies'],
      writingFlaws: ['[Medium] Overuse of passive voice in policy analysis sections'],
      strategicGaps: ['[High] No recommended policy harmonization roadmap'],
      gccGaps: [],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 4, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `The GCC is experiencing a divergent AI regulatory environment, with the UAE pioneering a pro-innovation, principles-based framework while Saudi Arabia is developing sector-specific guidance under SDAIA.\n\nThis policy fragmentation creates compliance complexity for multinational technology firms operating across GCC markets and presents an opportunity for regional harmonization leadership.`,
        },
        {
          heading: 'Regulatory Landscape',
          body: `UAE: The UAE AI Office has published a voluntary AI Ethics Framework and is developing mandatory sectoral guidelines for healthcare and finance AI applications.\n\nSaudi Arabia: SDAIA's national AI strategy includes regulatory components. Financial sector AI governance is overseen by SAMA with guidance issued in 2024.`,
        },
        {
          heading: 'Disclaimer',
          isDisclaimer: true,
          body: `Policy landscape is subject to rapid change. Verify regulatory status before any compliance-based decisions.`,
        },
      ],
    },
    comments: [
      {
        id: 'c4',
        reportId: 'RPT-2026-0604',
        version: 'v1.0',
        section: 'Regulatory Landscape',
        text: 'Expand Bahrain and Oman coverage — currently UAE/KSA only which is not representative of the full GCC.',
        priority: 'High',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-04T09:30:00',
        status: 'sent to regeneration',
      },
    ],
  },
  {
    id: 'RPT-2026-0605',
    title: 'Global Semiconductor Supply Chain: Resilience Strategies Post-2025 Export Controls',
    version: 'v1.3',
    status: ReportStatus.NeedsRevision,
    humanStatus: 'Needs Revision',
    aiScore: 72.1,
    aiGrade: 'Bronze',
    commentCount: 4,
    lastUpdated: '2026-06-01T14:20:00',
    publishReady: false,
    aiReview: {
      scores: {
        overall_score: 72.1,
        grade: 'Bronze',
        components: {
          research_quality: 75,
          strategic_insight: 78,
          source_quality: 65,
          writing_quality: 80,
          design_quality: 70,
          executive_readiness: 65,
        },
      },
      recommendations: {
        strengths: [
          'Comprehensive mapping of key export control provisions',
          'Good identification of alternative sourcing geographies',
        ],
        weaknesses: [
          'Analysis is heavily US-centric; missing European and Japanese supplier perspectives',
          'No financial impact quantification of supply chain disruption scenarios',
          'Data as of Q3 2024 — may be stale given rapid regulatory changes',
        ],
        priority_improvements: [
          {
            issue: 'US-centric analysis',
            impact: 'Misses critical ASML, TSMC, Tokyo Electron supply chain dependencies',
            suggested_fix: 'Add European and Japanese supplier vulnerability analysis',
            priority_level: 'High',
          },
          {
            issue: 'No financial scenario modeling',
            impact: 'Decision-makers cannot quantify risk',
            suggested_fix: 'Build 3-scenario supply chain cost model (base, adverse, severe)',
            priority_level: 'High',
          },
        ],
        executive_readiness: {
          board_members: false,
          ministers: false,
          ceos: false,
          sovereign_wealth_funds: false,
          senior_executives: true,
          justification: 'Currently suitable only for senior technical/operational executives.',
        },
      },
      dataGaps: ['[High] No TSMC advanced node allocation data post-2025 rules'],
      writingFlaws: ['[High] Executive summary uses technical acronyms without explanation'],
      strategicGaps: ['[High] No GCC investment opportunity framing in semiconductor supply chain'],
      gccGaps: ['No connection to KSA Vision 2030 semiconductor aspirations'],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — DRAFT — Internal Use Only',
      date: 'June 1, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `[DRAFT — Requires revision] The 2023–2025 US BIS export control regime has created significant fragmentation in global semiconductor supply chains. Advanced logic chips (sub-7nm), HBM memory, and EDA software now face layered export restrictions targeting China.`,
        },
        {
          heading: 'Export Control Framework',
          body: `The October 2023 and November 2024 BIS rule updates expanded restrictions to cover advanced AI chips, HBM memory, semiconductor manufacturing equipment, and EDA tools. TSMC, Samsung, and SK Hynix have implemented compliance programs.`,
        },
        {
          heading: 'Disclaimer',
          isDisclaimer: true,
          body: `DRAFT report. Do not distribute. BlueOcean internal research only.`,
        },
      ],
    },
    comments: [
      {
        id: 'c5',
        reportId: 'RPT-2026-0605',
        version: 'v1.3',
        section: 'Executive Summary',
        text: 'This executive summary needs a complete rewrite — remove all acronyms or spell them out.',
        priority: 'High',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-01T12:30:00',
        status: 'sent to regeneration',
      },
      {
        id: 'c6',
        reportId: 'RPT-2026-0605',
        version: 'v1.3',
        section: 'Executive Summary',
        text: 'Add European and Japanese supplier analysis. ASML is barely mentioned.',
        priority: 'High',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-01T12:38:00',
        status: 'sent to regeneration',
      },
      {
        id: 'c7',
        reportId: 'RPT-2026-0605',
        version: 'v1.3',
        section: 'Executive Summary',
        text: 'Need 3-scenario financial model for supply chain cost impact.',
        priority: 'High',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-01T12:45:00',
        status: 'sent to regeneration',
      },
      {
        id: 'c8',
        reportId: 'RPT-2026-0605',
        version: 'v1.3',
        section: 'Export Control Framework',
        text: 'Data is stale — update to reflect November 2025 BIS amendments.',
        priority: 'High',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-01T12:52:00',
        status: 'open',
      },
    ],
  },
  {
    id: 'RPT-2026-0606',
    title: 'Emerging Market Digital Banking: GCC Fintech Opportunity Sizing',
    version: 'v1.0',
    status: ReportStatus.Generated,
    humanStatus: 'Not Started',
    aiScore: 0,
    aiGrade: '—',
    commentCount: 0,
    lastUpdated: '2026-06-04T18:00:00',
    publishReady: false,
    aiReview: null,
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 4, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `GCC fintech is undergoing rapid transformation driven by regulatory innovation (ADGM, DIFC FinTech hive), smartphone penetration exceeding 95%, and a young demographic skew toward digital-first banking.\n\nTotal addressable market for digital banking services in GCC is estimated at $45B by 2030.`,
        },
        {
          heading: 'Market Overview',
          body: `UAE leads GCC fintech with 50+ licensed fintechs in DIFC and ADGM. Saudi Arabia's Vision 2030 financial sector development program has catalyzed 60%+ growth in fintech registrations since 2022.`,
        },
        { heading: 'Disclaimer', isDisclaimer: true, body: `BlueOcean Research. Internal use only. AI-generated draft, pending human review.` },
      ],
    },
    comments: [],
  },
  {
    id: 'RPT-2026-0607',
    title: 'Climate Tech Investment: MENA Carbon Market Development',
    version: 'v1.1',
    status: ReportStatus.Published,
    humanStatus: 'Approved',
    aiScore: 89.5,
    aiGrade: 'Silver',
    commentCount: 2,
    lastUpdated: '2026-06-02T11:00:00',
    publishReady: true,
    aiReview: {
      scores: {
        overall_score: 89.5,
        grade: 'Silver',
        components: {
          research_quality: 90,
          strategic_insight: 91,
          source_quality: 86,
          writing_quality: 92,
          design_quality: 88,
          executive_readiness: 90,
        },
      },
      recommendations: {
        strengths: [
          'Timely analysis aligned with COP29 agenda',
          'Strong quantitative market sizing with scenario modeling',
          'Excellent GCC relevance framing throughout',
        ],
        weaknesses: [
          'Voluntary carbon market integrity concerns not addressed',
          'No analysis of Article 6 Paris Agreement implications',
        ],
        priority_improvements: [
          {
            issue: 'Carbon credit quality/integrity gap',
            impact: 'Recommendations may lead to reputational risk for investors',
            suggested_fix: 'Add section on additionality standards and ICVCM Core Carbon Principles',
            priority_level: 'Medium',
          },
        ],
        executive_readiness: {
          board_members: true,
          ministers: true,
          ceos: true,
          sovereign_wealth_funds: true,
          senior_executives: true,
          justification: 'Excellent executive readiness. Suitable for all target audiences.',
        },
      },
      dataGaps: [],
      writingFlaws: [],
      strategicGaps: [],
      gccGaps: [],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 2, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `The MENA voluntary carbon market is projected to reach $2.5B by 2030, driven by Saudi Arabia's PIF net-zero commitments, UAE Carbon Credits Exchange launch, and growing multinational demand for credible MENA-sourced offsets.`,
        },
        {
          heading: 'Market Sizing',
          body: `Current MENA voluntary carbon market: ~$180M (2025). Base case projection: $1.2B (2027), $2.5B (2030). Bull case: $4B (2030) driven by Article 6 bilateral agreements.`,
        },
        { heading: 'Disclaimer', isDisclaimer: true, body: `BlueOcean Research. Published report — June 2026.` },
      ],
    },
    comments: [
      {
        id: 'c9',
        reportId: 'RPT-2026-0607',
        version: 'v1.1',
        section: 'Market Sizing',
        text: 'Bull case of $4B needs to be caveated more prominently.',
        priority: 'Medium',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-02T10:15:00',
        status: 'resolved',
      },
      {
        id: 'c10',
        reportId: 'RPT-2026-0607',
        version: 'v1.1',
        section: 'Executive Summary',
        text: 'Excellent framing. Approved for publication.',
        priority: 'Low',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-02T10:45:00',
        status: 'resolved',
      },
    ],
  },
  {
    id: 'RPT-2026-0608',
    title: 'Deep Tech VC: Portfolio Construction for Emerging Market Investors',
    version: 'v1.0',
    status: ReportStatus.NeedsHumanReview,
    humanStatus: 'In Progress',
    aiScore: 83.7,
    aiGrade: 'Silver',
    commentCount: 1,
    lastUpdated: '2026-06-04T16:00:00',
    publishReady: false,
    aiReview: {
      scores: {
        overall_score: 83.7,
        grade: 'Silver',
        components: {
          research_quality: 85,
          strategic_insight: 87,
          source_quality: 80,
          writing_quality: 88,
          design_quality: 82,
          executive_readiness: 80,
        },
      },
      recommendations: {
        strengths: [
          'Strong portfolio construction framework with EM context',
          'Clear risk-adjusted return modeling across deep tech verticals',
          'Good GCC investor perspective integration',
        ],
        weaknesses: [
          'Limited discussion of currency hedging for EM deep tech investments',
          'No analysis of co-investment structures with US/European VC',
        ],
        priority_improvements: [
          {
            issue: 'Currency risk not addressed',
            impact: 'GCC investors face significant FX exposure',
            suggested_fix: 'Add section on hedging strategies and currency risk quantification',
            priority_level: 'High',
          },
        ],
        executive_readiness: {
          board_members: true,
          ministers: false,
          ceos: true,
          sovereign_wealth_funds: true,
          senior_executives: true,
          justification: 'Suitable for board, CEO, and SWF audiences.',
        },
      },
      dataGaps: ['[Medium] No EM deep tech IRR benchmark data vs global VC'],
      writingFlaws: ['[Low] Section 4 conclusion paragraph is redundant'],
      strategicGaps: ['[Medium] Co-investment structures with tier-1 VCs not analyzed'],
      gccGaps: [],
    },
    reportContent: {
      brand: 'BlueOcean',
      label: 'Deep Research Report — Confidential',
      date: 'June 4, 2026',
      sections: [
        {
          heading: 'Executive Summary',
          body: `Deep technology venture capital is experiencing a bifurcation: tier-1 US and European funds are increasingly inaccessible to emerging market LPs, while regional deep tech ecosystems in MENA, Southeast Asia, and India are generating independent deal flow with risk-return profiles comparable to Series A/B global benchmarks.`,
        },
        {
          heading: 'Portfolio Construction Framework',
          body: `Recommended allocation: 40% global tier-1 co-investments, 35% regional champions (MENA, India, SEA), 25% early-stage local ecosystem (UAE, KSA, Qatar).\n\nRisk-adjusted return target: 18% net IRR over 10-year horizon at 2.5× MOIC.`,
        },
        { heading: 'Disclaimer', isDisclaimer: true, body: `BlueOcean Research. Internal use only. Not investment advice.` },
      ],
    },
    comments: [
      {
        id: 'c11',
        reportId: 'RPT-2026-0608',
        version: 'v1.0',
        section: 'Portfolio Construction Framework',
        text: 'The 18% net IRR target needs a benchmark comparison — what is the EM PE/VC average?',
        priority: 'Medium',
        reviewer: 'Senior Reviewer',
        timestamp: '2026-06-04T15:30:00',
        status: 'open',
      },
    ],
  },
];
